# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'Acronyms' do
pod "AFNetworking", "~> 2.0"
pod 'MBProgressHUD', '~> 0.9.1'

end

target 'AcronymsTests' do

end

